# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html

title: SIDL Challenge
short_description: SIDL Restoration Challenge
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
submission_guidelines: templates/submission_guidelines.html
image: logo.jpg

evaluation_script: evaluation_script.zip
remote_evaluation: False
published: True

start_date: 2025-03-21 00:00:00
end_date: 2029-05-31 23:59:59

leaderboard:
  - id: 1
    schema: >
      {
        "labels": ["Metric1", "Metric2", "Total"],
        "default_order_by": "Total",
        "metadata": {
          "Metric1": {
            "sort_ascending": true,
            "description": "Metric 1 description"
          },
          "Metric2": {
            "sort_ascending": false,
            "description": "Metric 2 description"
          }
        }
      }

challenge_phases:
  - id: 1
    name: SIDL Challenge Phase
    description: templates/challenge_phase_1_description.html
    leaderboard_public: True
    is_public: True
    challenge: 1
    is_active: True
    start_date: 2025-03-21 00:00:00
    end_date: 2029-05-31 23:59:59
    test_annotation_file: annotations/test_annotations_devsplit.json
    codename: dev
    max_submissions_per_day: 5
    max_submissions_per_month: 50
    max_submissions: 50
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
    submission_meta_attributes: []
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".json, .zip"

dataset_splits:
  - id: 1
    name: Dev Split
    codename: dev_split

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
    show_execution_time: True
    show_leaderboard_by_latest_submission: True
